secretKey: &secretKey
  factory: prompto.security.AwsKMSSecretKeyFactory
  alias: prompto/seed
  awsRegion: us-east-1

secret: &secret AQICAHiWGTkxd74dNcn82U2E7Y/aoKsK58VZ26N/OSsr01yfrAGaKPSMtmv7mB9f32G1Epn9AAAAajBoBgkqhkiG9w0BBwagWzBZAgEAMFQGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMo2VIeuZWJGxBFgZDAgEQgCdm21syTkfHO+7i+KgrxobSHr7OgoulC47YucABjKpTY9Od6vUGjcU=

mongoStore: &atlasMongoStore
  factory: prompto.store.mongo.MongoStoreFactory
  replicaSet:
    name: atlas-12n3js-shard-0
    nodes:
      - host: cluster0-shard-00-00.cp8j5.mongodb.net
        port: 27017
      - host: cluster0-shard-00-01.cp8j5.mongodb.net
        port: 27017
      - host: cluster0-shard-00-02.cp8j5.mongodb.net
        port: 27017
  user: admin
  secretKey:
    <<: *secretKey
    secret: *secret

dataStore:
  <<: *atlasMongoStore
  dbName: PROMPTO-DATA

applicationName: WebSite
applicationVersion: 0.0.10
serverAboutToStart: start_WebSite

http:
  publicAddress: eric.prompto.cloud
  protocol: https
  port: 443
  redirectFrom: 80
  keyStore:
    provider:
      factory: prompto.security.FileKeyStoreFactory
      file: /keystore.jks
    secretKey:
      <<: *secretKey
      secret: *secret
  trustStore:
    provider:
      factory: prompto.security.FileKeyStoreFactory
      file: /truststore.jks
    secretKey:
      <<: *secretKey
      secret: *secret
